// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'first api key',
    appId: '1:803500116731:web:7df2f92187f5eb12687e5e',
    messagingSenderId: '803500116731',
    projectId: 'reminderapp-c75c8',
    authDomain: 'reminderapp-c75c8.firebaseapp.com',
    storageBucket: 'reminderapp-c75c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'second api key',
    appId: '1:803500116731:android:77c9cdd1820666ce687e5e',
    messagingSenderId: '803500116731',
    projectId: 'reminderapp-c75c8',
    storageBucket: 'reminderapp-c75c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'third api key',
    appId: '1:803500116731:ios:beb0c4a3aeee672c687e5e',
    messagingSenderId: '803500116731',
    projectId: 'reminderapp-c75c8',
    storageBucket: 'reminderapp-c75c8.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'fourth api key',
    appId: '1:803500116731:ios:beb0c4a3aeee672c687e5e',
    messagingSenderId: '803500116731',
    projectId: 'reminderapp-c75c8',
    storageBucket: 'reminderapp-c75c8.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );
}
